<?xml version="1.0"?>
<package format="3">
  <name>hsr_policy_client</name>
  <version>0.1.0</version>
  <description>ROS 2 policy client for the HSR evaluation runtime.</description>

  <maintainer email="ookubo-takuya069@g.ecc.u-tokyo.ac.jp">Takuya Okubo</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>geometry_msgs</depend>
  <depend>hsr_policy_client_interfaces</depend>
  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>tmc_control_msgs</depend>
  <depend>trajectory_msgs</depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
